import type {
  MockAd,
  MockAdAccount,
  MockAdSet,
  MockCampaign,
} from '@/mock-data/types';

export const MOCK_AD_ACCOUNTS: MockAdAccount[] = [
  {
    id: 'act_meta_129440001',
    name: 'Wod Armour',
    platform: 'meta',
  },
  {
    id: 'act_meta_129440002',
    name: 'Dar Global',
    platform: 'meta',
  },
  {
    id: 'act_google_55821031',
    name: 'Hyperice',
    platform: 'google',
  },
];

export const MOCK_CAMPAIGNS: MockCampaign[] = [
  {
    id: 'cmp_meta_1001',
    adAccountId: 'act_meta_129440001',
    name: 'Wod Armour | Spring Prospecting',
    status: 'ACTIVE',
    metrics: {
      impressions: '892.4K',
      clicks: '24.8K',
      spend: '$28.6K',
      reach: '401.2K',
      revenue: '$96.8K',
      ctr: '2.78%',
      cpc: '$1.15',
      roas: '3.39x',
    },
  },
  {
    id: 'cmp_meta_1002',
    adAccountId: 'act_meta_129440001',
    name: 'Wod Armour | Retargeting Push',
    status: 'PAUSED',
    metrics: {
      impressions: '416.9K',
      clicks: '16.2K',
      spend: '$19.4K',
      reach: '168.5K',
      revenue: '$74.1K',
      ctr: '3.89%',
      cpc: '$1.20',
      roas: '3.82x',
    },
  },
  {
    id: 'cmp_meta_2001',
    adAccountId: 'act_meta_129440002',
    name: 'Dar Global | UAE Lead Gen',
    status: 'ACTIVE',
    metrics: {
      impressions: '631.5K',
      clicks: '13.7K',
      spend: '$24.8K',
      reach: '312.6K',
      revenue: '$88.9K',
      ctr: '2.17%',
      cpc: '$1.81',
      roas: '3.58x',
    },
  },
  {
    id: 'cmp_meta_2002',
    adAccountId: 'act_meta_129440002',
    name: 'Dar Global | Investor Nurture',
    status: 'WITH_ISSUES',
    metrics: {
      impressions: '357.2K',
      clicks: '8.5K',
      spend: '$17.3K',
      reach: '149.1K',
      revenue: '$56.4K',
      ctr: '2.38%',
      cpc: '$2.03',
      roas: '3.26x',
    },
  },
  {
    id: 'cmp_google_3001',
    adAccountId: 'act_google_55821031',
    name: 'Hyperice | Brand Search',
    status: 'ENDED',
    metrics: {
      impressions: '704.3K',
      clicks: '18.1K',
      spend: '$21.6K',
      reach: '298.4K',
      revenue: '$61.9K',
      ctr: '2.57%',
      cpc: '$1.19',
      roas: '2.87x',
    },
  },
  {
    id: 'cmp_google_3002',
    adAccountId: 'act_google_55821031',
    name: 'Hyperice | Recovery Device Shopping',
    status: 'ACTIVE',
    metrics: {
      impressions: '518.6K',
      clicks: '12.9K',
      spend: '$16.7K',
      reach: '226.8K',
      revenue: '$49.7K',
      ctr: '2.49%',
      cpc: '$1.29',
      roas: '2.98x',
    },
  },
];

export const MOCK_AD_SETS: MockAdSet[] = [
  {
    id: 'adset_meta_1001_a',
    campaignId: 'cmp_meta_1001',
    name: 'Broad Athletes 18-34',
    status: 'ACTIVE',
    metrics: {
      impressions: '328.4K',
      clicks: '9.5K',
      spend: '$10.4K',
      reach: '156.8K',
      revenue: '$39.8K',
      ctr: '2.89%',
      cpc: '$1.09',
      roas: '3.83x',
    },
  },
  {
    id: 'adset_meta_1001_b',
    campaignId: 'cmp_meta_1001',
    name: 'CrossFit Interest Stack',
    status: 'ACTIVE',
    metrics: {
      impressions: '264.7K',
      clicks: '7.4K',
      spend: '$9.1K',
      reach: '122.2K',
      revenue: '$31.6K',
      ctr: '2.80%',
      cpc: '$1.23',
      roas: '3.47x',
    },
  },
  {
    id: 'adset_meta_1002_a',
    campaignId: 'cmp_meta_1002',
    name: 'Viewed Product 30D',
    status: 'PAUSED',
    metrics: {
      impressions: '189.6K',
      clicks: '6.8K',
      spend: '$8.6K',
      reach: '77.4K',
      revenue: '$28.4K',
      ctr: '3.59%',
      cpc: '$1.26',
      roas: '3.30x',
    },
  },
  {
    id: 'adset_meta_2001_a',
    campaignId: 'cmp_meta_2001',
    name: 'Dubai High Intent Leads',
    status: 'ACTIVE',
    metrics: {
      impressions: '301.7K',
      clicks: '6.5K',
      spend: '$11.8K',
      reach: '148.2K',
      revenue: '$45.7K',
      ctr: '2.15%',
      cpc: '$1.82',
      roas: '3.87x',
    },
  },
  {
    id: 'adset_meta_2002_a',
    campaignId: 'cmp_meta_2002',
    name: 'Warm Investor Retargeting',
    status: 'WITH_ISSUES',
    metrics: {
      impressions: '143.8K',
      clicks: '3.2K',
      spend: '$7.1K',
      reach: '61.5K',
      revenue: '$19.8K',
      ctr: '2.23%',
      cpc: '$2.22',
      roas: '2.79x',
    },
  },
  {
    id: 'adset_google_3001_a',
    campaignId: 'cmp_google_3001',
    name: 'US Brand Core Terms',
    status: 'ENDED',
    metrics: {
      impressions: '242.5K',
      clicks: '6.2K',
      spend: '$7.8K',
      reach: '105.4K',
      revenue: '$18.4K',
      ctr: '2.56%',
      cpc: '$1.26',
      roas: '2.36x',
    },
  },
  {
    id: 'adset_google_3002_a',
    campaignId: 'cmp_google_3002',
    name: 'Recovery Device Best Sellers',
    status: 'ACTIVE',
    metrics: {
      impressions: '214.3K',
      clicks: '5.4K',
      spend: '$6.9K',
      reach: '92.6K',
      revenue: '$24.6K',
      ctr: '2.52%',
      cpc: '$1.28',
      roas: '3.57x',
    },
  },
];

export const MOCK_ADS: MockAd[] = [
  {
    id: 'ad_meta_1001_a_01',
    adSetId: 'adset_meta_1001_a',
    name: 'Wod Armour | Rope Climb Static',
    status: 'ACTIVE',
    headline: 'Built for heavy training days',
    primaryText:
      'Showcase the grip and durability story with high-contrast gym photography and a clear equipment-first angle.',
    destination: 'Product page',
    metrics: {
      impressions: '112.8K',
      clicks: '3.6K',
      spend: '$4.1K',
      reach: '54.7K',
      revenue: '$16.9K',
      ctr: '3.19%',
      cpc: '$1.14',
      roas: '4.12x',
    },
    media: [
      {
        id: 'media_ad_meta_1001_a_01_1',
        title: 'Athlete climbing rope',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1400&q=80',
        aspectRatio: '4 / 5',
      },
      {
        id: 'media_ad_meta_1001_a_01_2',
        title: 'Training equipment close-up',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1400&q=80',
        aspectRatio: '4 / 5',
      },
    ],
    detailMetrics: [
      { id: 'conversions', label: 'Conversions', value: '428' },
      { id: 'cpa', label: 'CPA', value: '$9.58' },
      { id: 'hook-rate', label: 'Hook Rate', value: '34.7%' },
      { id: 'landing-rate', label: 'Landing Page View Rate', value: '79.2%' },
    ],
  },
  {
    id: 'ad_meta_1001_b_01',
    adSetId: 'adset_meta_1001_b',
    name: 'Wod Armour | Gym Chalk Carousel',
    status: 'ACTIVE',
    headline: 'Strong lift days start here',
    primaryText:
      'Lead with tactile product shots and a punchy offer to move broad-interest traffic into the cart.',
    destination: 'Collection page',
    metrics: {
      impressions: '87.4K',
      clicks: '2.8K',
      spend: '$3.7K',
      reach: '42.1K',
      revenue: '$13.9K',
      ctr: '3.20%',
      cpc: '$1.32',
      roas: '3.76x',
    },
    media: [
      {
        id: 'media_ad_meta_1001_b_01_1',
        title: 'Chalk bowl product still',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1517963628607-235ccdd5476c?auto=format&fit=crop&w=1400&q=80',
        aspectRatio: '1 / 1',
      },
      {
        id: 'media_ad_meta_1001_b_01_2',
        title: 'Athlete preparing hands',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1518310383802-640c2de311b2?auto=format&fit=crop&w=1400&q=80',
        aspectRatio: '1 / 1',
      },
    ],
    detailMetrics: [
      { id: 'conversions', label: 'Conversions', value: '302' },
      { id: 'cpa', label: 'CPA', value: '$12.25' },
      { id: 'hook-rate', label: 'Hook Rate', value: '29.4%' },
      { id: 'carousel-swipe', label: 'Carousel Swipe Rate', value: '18.6%' },
    ],
  },
  {
    id: 'ad_meta_1002_a_01',
    adSetId: 'adset_meta_1002_a',
    name: 'Wod Armour | Checkout Reminder',
    status: 'PAUSED',
    headline: 'Finish your setup before training',
    primaryText:
      'A conversion-focused reminder creative with product context and a lighter promo frame for warm audiences.',
    destination: 'Checkout',
    metrics: {
      impressions: '74.8K',
      clicks: '2.1K',
      spend: '$3.9K',
      reach: '31.9K',
      revenue: '$9.5K',
      ctr: '2.81%',
      cpc: '$1.86',
      roas: '2.44x',
    },
    media: [
      {
        id: 'media_ad_meta_1002_a_01_1',
        title: 'Warm retargeting still',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1514996937319-344454492b37?auto=format&fit=crop&w=1400&q=80',
        aspectRatio: '4 / 5',
      },
      {
        id: 'media_ad_meta_1002_a_01_2',
        title: 'Product in gym bag',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=1400&q=80',
        aspectRatio: '4 / 5',
      },
    ],
    detailMetrics: [
      { id: 'conversions', label: 'Conversions', value: '131' },
      { id: 'cpa', label: 'CPA', value: '$29.77' },
      { id: 'hook-rate', label: 'Hook Rate', value: '21.3%' },
      { id: 'landing-rate', label: 'Landing Page View Rate', value: '72.8%' },
    ],
  },
  {
    id: 'ad_meta_2001_a_01',
    adSetId: 'adset_meta_2001_a',
    name: 'Dar Global | Tower Launch Video',
    status: 'ACTIVE',
    headline: 'Own the skyline before launch',
    primaryText:
      'A cinematic property teaser with aerial footage, architectural detail, and a lead-gen first CTA.',
    destination: 'Lead form',
    metrics: {
      impressions: '96.1K',
      clicks: '2.5K',
      spend: '$4.3K',
      reach: '48.8K',
      revenue: '$19.3K',
      ctr: '2.60%',
      cpc: '$1.72',
      roas: '4.48x',
    },
    media: [
      {
        id: 'media_ad_meta_2001_a_01_1',
        title: 'Tower launch teaser',
        type: 'video',
        src: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
        posterSrc: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1400&q=80',
        aspectRatio: '9 / 16',
      },
      {
        id: 'media_ad_meta_2001_a_01_2',
        title: 'Exterior tower still',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1400&q=80',
        aspectRatio: '9 / 16',
      },
    ],
    detailMetrics: [
      { id: 'conversions', label: 'Qualified Leads', value: '184' },
      { id: 'cpa', label: 'Cost per Lead', value: '$23.37' },
      { id: 'thumb-stop', label: 'Thumb-Stop Rate', value: '37.1%' },
      { id: 'video-views', label: '15s Video Views', value: '28.4K' },
    ],
  },
  {
    id: 'ad_meta_2002_a_01',
    adSetId: 'adset_meta_2002_a',
    name: 'Dar Global | Investor Proof Points',
    status: 'WITH_ISSUES',
    headline: 'See what high-intent buyers value',
    primaryText:
      'An investor-focused proof creative built around lifestyle photography, market cues, and urgency messaging.',
    destination: 'Lead form',
    metrics: {
      impressions: '58.6K',
      clicks: '1.2K',
      spend: '$3.3K',
      reach: '24.9K',
      revenue: '$6.4K',
      ctr: '2.05%',
      cpc: '$2.75',
      roas: '1.92x',
    },
    media: [
      {
        id: 'media_ad_meta_2002_a_01_1',
        title: 'Interior luxury still',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1400&q=80',
        aspectRatio: '4 / 5',
      },
      {
        id: 'media_ad_meta_2002_a_01_2',
        title: 'Property amenities still',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1400&q=80',
        aspectRatio: '4 / 5',
      },
    ],
    detailMetrics: [
      { id: 'conversions', label: 'Qualified Leads', value: '62' },
      { id: 'cpa', label: 'Cost per Lead', value: '$53.23' },
      { id: 'hook-rate', label: 'Hook Rate', value: '18.9%' },
      { id: 'lead-form-rate', label: 'Lead Form Completion Rate', value: '11.8%' },
    ],
  },
  {
    id: 'ad_google_3001_a_01',
    adSetId: 'adset_google_3001_a',
    name: 'Hyperice | Recovery Ritual Cutdown',
    status: 'ENDED',
    headline: 'Recovery that keeps up with training',
    primaryText:
      'Short-form creative featuring at-home recovery moments, product close-ups, and a direct product-page CTA.',
    destination: 'Product page',
    metrics: {
      impressions: '66.3K',
      clicks: '1.6K',
      spend: '$3.1K',
      reach: '29.4K',
      revenue: '$6.6K',
      ctr: '2.41%',
      cpc: '$1.94',
      roas: '2.14x',
    },
    media: [
      {
        id: 'media_ad_google_3001_a_01_1',
        title: 'Recovery ritual video',
        type: 'video',
        src: 'https://storage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4',
        posterSrc: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=1400&q=80',
        aspectRatio: '16 / 9',
      },
      {
        id: 'media_ad_google_3001_a_01_2',
        title: 'Product texture still',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1400&q=80',
        aspectRatio: '16 / 9',
      },
    ],
    detailMetrics: [
      { id: 'conversions', label: 'Purchases', value: '118' },
      { id: 'cpa', label: 'CPA', value: '$26.27' },
      { id: 'thumb-stop', label: 'Thumb-Stop Rate', value: '22.8%' },
      { id: 'video-views', label: '10s Video Views', value: '17.2K' },
    ],
  },
  {
    id: 'ad_google_3002_a_01',
    adSetId: 'adset_google_3002_a',
    name: 'Hyperice | Venom 2 Listing',
    status: 'ACTIVE',
    headline: 'Heat and vibration in one reset',
    primaryText:
      'A product-led creative pairing clean device imagery with benefits-first copy for shoppers already in-market.',
    destination: 'Product page',
    metrics: {
      impressions: '81.7K',
      clicks: '2.4K',
      spend: '$3.5K',
      reach: '35.8K',
      revenue: '$13.9K',
      ctr: '2.94%',
      cpc: '$1.46',
      roas: '3.98x',
    },
    media: [
      {
        id: 'media_ad_google_3002_a_01_1',
        title: 'Product demo still',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1400&q=80',
        aspectRatio: '1 / 1',
      },
      {
        id: 'media_ad_google_3002_a_01_2',
        title: 'Recovery use-case video',
        type: 'video',
        src: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
        posterSrc: 'https://images.unsplash.com/photo-1546483875-ad9014c88eba?auto=format&fit=crop&w=1400&q=80',
        aspectRatio: '1 / 1',
      },
    ],
    detailMetrics: [
      { id: 'conversions', label: 'Purchases', value: '244' },
      { id: 'cpa', label: 'CPA', value: '$14.34' },
      { id: 'hook-rate', label: 'Hook Rate', value: '31.8%' },
      { id: 'landing-rate', label: 'Landing Page View Rate', value: '81.4%' },
    ],
  },
];
