import { Providers } from '@/components/providers';
import '@/styles/globals.css';
import { cn } from '@/utils/utils';
import type { Metadata } from 'next';
import { Inter, JetBrains_Mono, Source_Serif_4 } from 'next/font/google';

const fontSans = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});

const fontSerif = Source_Serif_4({
  subsets: ['latin'],
  variable: '--font-serif',
});

const fontMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(
        'h-full antialiased',
        fontSans.variable,
        fontSerif.variable,
        fontMono.variable
      )}
    >
      <body
        className={cn(
          'flex min-h-full flex-col',
          process.env.NODE_ENV === 'development' && 'debug-screens'
        )}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
